
stages:
  - stage: build_stage
    displayName: "Build"
    jobs:
      - job: build_job
        steps:
          - task: UseDotNet@2
            displayName: "Install .NET Core SDK"
            inputs:
              version: 6.x
              performMultiLevelLookup: true
              includePreviewVersions: true # Required for preview versions

          - task: DotNetCoreCLI@2
            displayName: "Dotnet Restore"
            inputs:
              command: "restore"
              feedsToUse: "select"
              feedRestore: "store/feedName"
              projects: "**/*.csproj"
              includeNuGetOrg: true

          - task: DotNetCoreCLI@2
            displayName: "Dotnet Build"
            inputs:
              projects: src.sln # solution file or project files
              command: "build"
              arguments: "--configuration $(buildConfiguration)"

          # Publish projects to specified folder.
          - task: DotNetCoreCLI@2
            displayName: "Dotnet Publish"
            inputs:
              command: "publish"
              publishWebProjects: true
              projects: "**/*.csproj"
              arguments: "-o $(Build.ArtifactStagingDirectory)"
              zipAfterPublish: true
              modifyOutputPath: true
            # this code takes all the files in $(Build.ArtifactStagingDirectory) and uploads them as an artifact of your build.
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: "$(Build.ArtifactStagingDirectory)"
              artifactName: "artefactName"